# Generated by Django 3.2.9 on 2021-11-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('urlsToLogos_small', models.CharField(max_length=1000)),
                ('urlsToLogos_medium', models.CharField(max_length=1000)),
                ('urlsToLogos_large', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlToImage', models.CharField(blank=True, max_length=1000, null=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getNews.source')),
            ],
        ),
    ]
